import { createHmac, timingSafeEqual } from 'crypto'

const SECRET = process.env.NEXTAUTH_SECRET || ''

/** Generate a short-lived (15 min) HMAC-signed token for large-file uploads.
 *  Used to authenticate requests to upload.modskinslol.com which bypasses
 *  Cloudflare's 100 MB proxy upload limit. */
export function generateUploadToken(): string {
  if (!SECRET) throw new Error('NEXTAUTH_SECRET not set')
  const expires = Date.now() + 15 * 60 * 1000 // 15 minutes
  const payload = `upload:${expires}`
  const sig = createHmac('sha256', SECRET).update(payload).digest('hex')
  return `${expires}.${sig}`
}

/** Verify a token generated by generateUploadToken. Returns true if valid. */
export function verifyUploadToken(token: string): boolean {
  if (!SECRET || !token) return false
  try {
    const dotIdx = token.indexOf('.')
    if (dotIdx === -1) return false
    const expiresStr = token.slice(0, dotIdx)
    const sig = token.slice(dotIdx + 1)
    const expires = parseInt(expiresStr, 10)
    if (isNaN(expires) || Date.now() > expires) return false
    const payload = `upload:${expiresStr}`
    const expectedSig = createHmac('sha256', SECRET).update(payload).digest('hex')
    const sigBuf = Buffer.from(sig, 'hex')
    const expectedBuf = Buffer.from(expectedSig, 'hex')
    if (sigBuf.length !== expectedBuf.length) return false
    return timingSafeEqual(sigBuf, expectedBuf)
  } catch {
    return false
  }
}
